### ISSUE TITLE
Latest Version doesn't work on Centos 6.6

### ISSUE THREAD

**Issue by pirsquare** [logentries/le#109]
le monitor --debug
<pre>
Following /var/log/messages
Opening connection data.logentries.com:443
Caught unknown error zero length field name in format while sending line: 123
Traceback (most recent call last):
  File "/usr/share/logentries/logentries/le.py", line 1417, in monitorlogs
    self._send_line(line)
  File "/usr/share/logentries/logentries/le.py", line 1402, in _send_line
    self.transport.send(self.formatter.format_line(line))
  File "/usr/share/logentries/logentries/formatters.py", line 46, in format_line
    line)
ValueError: zero length field name in format
</pre>

Python: 2.6.6

Sidenote: Are there any straightforward ways to install older versions of le agent?

**Comment by pirsquare** [comment]
This breaks: https://github.com/logentries/le/commit/4b0571c123044ff7ec7a5d8741aeaa82aeaf4968 .

**Comment by vilda** [comment]
Will have a look ASAP, thanks! There is no way to downgrade easily although we have a ticket to enable it.

**Comment by pirsquare** [comment]
Closing this since PR merged https://github.com/logentries/le/pull/110
