### ISSUE TITLE
Define agent log format via agent config

### ISSUE THREAD

**Issue by mjsilva** [logentries/le#123]
Hi,

The logs headers  that come from the agent are too verbose. Making it hard/impossible to read.

See this example of a log line:
````
» 13 Jul 2015 23:14:07.091  <14>1 2015-07-13T13:14:02.239385Z sk-cron-i-2553a9fb.int.live.aws.theiconic.com.au sk_catalog_message_update - - - hostname=sk-cron-i-2553a9fb.int.live.aws.theiconic.com.au appname=sk_catalog_message_update     > Message 6043792: updated 1 documents Context
````

The message is only ````Message 6043792: updated 1 documents Context```` the whole header carries way to much useless info.

Here is our agent config:
````
[Main] 
user-key = xxxxxxx
hostname = sk-cron-i-2553a9fb.example.com
pull-server-side-config = False

[sk_catalog_message_update] 
path = /var/www/sk/data/logs/searchkeeper_catalog_message_update.log 
token = xxxxxxx

[sk_stats_update] 
path = /var/www/sk/data/logs/searchkeeper_stats_operational_update.log 
token = xxxxxxx

[syslog] 
path = /var/log/syslog 
token = xxxxxxx
````

Ideally one should be able to define the format on the log config.

Thanks

**Comment by jtbuchanan** [comment]
Hello, 
This feature request is also currently on the Trello board:
https://trello.com/c/6FlcK9Ri/94-ability-to-turn-off-syslog-formatting-when-using-agent-configuration-file

Thank you

**Comment by msimon** [comment]
Hello

If I can put my two cents in, I don't think logentries should try to implement RFC 5424 format.
This format is suppose to be used by the application that generate the logs. Logentries just being a transporter, it does not really make sense for it to implement it.

* The major issue with that is that if I do implement RFC 5424 in my log, your formatter will actually mess with my log.

Here is why:
(Example from https://tools.ietf.org/html/rfc5424#section-6.5)

> <34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8

> In this example, the VERSION is 1 and the Facility has the value of 4.  The Severity is 2.  The message was created on 11 October 2003 at 10:14:15pm UTC, 3 milliseconds into the next second.  The message originated from a host that identifies itself as "mymachine.example.com".  The APP-NAME is "su" and the PROCID is unknown.  The MSGID is "ID47".  The MSG is "'su root' failed for lonvick...", encoded in UTF-8.  The encoding is defined by the BOM. There is no STRUCTURED-DATA present in the message; this is indicated by "-" in the STRUCTURED-DATA field.

If my log looks like that before being formated by logentries, this is how it will look after:

> <14>1 {dt}Z {hostname} {appname} - {msgid} - hostname={hostname} appname={appname} <34>1 2003-10-11T22:14:15.003Z mymachine.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8

All the information that I provide following RFC 5424 just got overwrite by your data (which are incorrect). My priority is not 14 but 34, my version is 1 but could be different, datetime could have another format and another value, same goes for most of the data.

* In the case I do not implement RFC 5424 then the data you append to my log are still untrue. The idea behind RFC 5424 is to give meaning to log, appending untrue value make the implementation useless.

IMO, the only way to modify a log is to modify the MSG part.
The formatter that I will find the most interesting would be:
'{line} -- token={token} hostname={hostname} appname={appname}' with the correct condition to only append no-empty value.

Cheers

**Comment by billputer** [comment]
Pull request #125 was just merged in, so you can now specify "formatter = plain" in your configuration file. This will simply pass the message on, without modifying the log format.

I'd prefer that this were the default, but adding it as an option retains the existing behavior without breaking anyone's current setup.

**Comment by msimon** [comment]
@billputer saw that and I'm currently using it with another formatter. Thanks for that!

The plain default make sense for a simple deployment, but for a autoscaling env the default should be displaying hostname and appname.

**Comment by vilda** [comment]
Hey @msimon, thanks for your comments. I don't think RFC 5424 is supposed to be used by applications. Actually, I'm not aware of any standard Unix application that would produce logs in RFC 5424 (apart from syslog).

Our assumption that bigger environments will use syslog proved to be wrong. Users prefer the agent in most (if not all) cases. We had to adapt to that and make RFC 5424 default.

If your application logs include all needed fields out of the box, use the plain format kindly provided by @billputer. We will extend the agent to support user-provided formatters soon.

Thanks!

**Comment by msimon** [comment]
I don't understand to which of your users this is useful. The information that you are providing following the RFC 5424 cannot be useful to the end user. The priority, timestamp, msgid, version are all incorrect (it is hardcoded in the formatter). If you want to provide hostname and appname (and token) no need to implement it, it can be just appended/prepended.

It's not a important at all, I already fix this issue personally. I'm just being curious.

Cheers
