### ISSUE TITLE
Error: Element not found when le follow file

### ISSUE THREAD

**Issue by martez81** [logentries/le#164]
For some reason I can't add additional files to logentries. I keep getting "Error: Element not found" when executing `le follow /path/to/file`, tried with rel and abs path.

le --version = 1.4.29

**Comment by martez81** [comment]
Silly me, forgot running it as super user.

**Comment by vilda** [comment]
Hi @martez81 can you share more information about how is this happening? If you run it as ordinary user then your local configuration is being used. If the file in ~/.le/config is empty then there should be a better error message than this.

**Comment by martez81** [comment]
@vilda I was running it as ordinary user and the config file exists with following contents:

```
[Main]
user-key = ###
agent-key = ###
hostname = ###
pull-server-side-config = True
metrics-mem = system
metrics-token = 
metrics-disk = sum
metrics-swap = system
metrics-space = /
metrics-vcpu = 
metrics-net = sum
metrics-interval = 5s
metrics-cpu = system
```

**Comment by vilda** [comment]
Thanks @martez81 I was able to reproduce it. I'll improve the message provided by the backend system.
