### ISSUE TITLE
Logging large events hinders agent.

### ISSUE THREAD

**Issue by UnquietCode** [logentries/le#180]
I have my logs set to use multi-line mode. When I'm logging by using the agent watching a file, if it encounters a large event (like a stack trace) the event never makes it to LE. Further, once this happens the agent seems to enter a stuck state where it won't log anything after that. This could be related to #77 as it results in missing data.

I have made a test file which is the largest I can append to the watched file before it breaks the agent. For me, the limit is 1307 characters. Anything larger blows up. Is this some kind of LogEntries limit on event payload sizes?

##### test.log
```plain
2016-04-11 22:14:06.691622 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
oooooooooooooooooooooooooooooooo
```

**Comment by vilda** [comment]
Thanks @UnquietCode - There's no limit around 1307. I'll look at it

**Comment by vilda** [comment]
Not having luck replicating this @UnquietCode Can you provide more details when you get a chance. Ideally post here relevant section of the configuration (without token) and "echo" command that will trigger this reported bug.

One option is to run the agent with debugging enabled, for example:

    le monitor --debug-transport-events

It will dump on console all entries it sends to Logentries. If it get stuck it won't display anyting.

**Comment by UnquietCode** [comment]
Thanks for the debugging tool. We were able to finally track this problem down to a networking misconfiguration. The ICMP protocol return path was being blocked, which was being used for PMTU calculations. The result was that any large frame was unable to be delivered over the network. To things like the logentrires daemon, it would have seemed like the TCP connection was ok, but then timed out without sending. With the changes to our network configuration, large log events are now being sent again by the daemon.
