### ISSUE TITLE
le register should be idempotent

### ISSUE THREAD

**Issue by willbarrett** [logentries/le#73]
If a server is already registered, this should not register a duplicate server with Logentries. This messes up automated provisioning of servers that need to send logs to Logentries.

**Comment by vilda** [comment]
It's not easy to detect if the server has already been registered or not. The agent saves the host key in the configuration file and checks for it during registration. If it's registered already, the registration fails.

Alternatively you can create static (local) configuration and avoid any registration. That's a good alternative for instances that are regularly stopped and started such as auto-scaling setup. 

Makes sense?

**Comment by willbarrett** [comment]
Perhaps you could add a command line flag that lets the registration fail silently, or documentation of the configuration file format? Right now there's not an obvious way to accomplish this from the information available online.

**Comment by vilda** [comment]
Ok, just added MR #78 :)

**Comment by willbarrett** [comment]
Awesome - thanks!

**Comment by vilda** [comment]
The update has been merged. We should be good now, the agent will be released in repos in a day or so.

**Comment by willbarrett** [comment]
Woohoo! Thank you!
