### ISSUE TITLE
README.md Documentation Updates

### ISSUE THREAD

**Issue by virgofx** [logentries/le#75]
From my latest installation and testing with the software ... here are some comments on the documentation. I figured it could be wrapped into a single issue.

1) The configuration path seems to be wrong. Configuration is located in the **proper** `/etc/le/config` location.
```
Local configuration

The agent stores configuration in ~/.le/config for ordinary users and in /root/le/config for root (daemon). It is created with init or reinit commands and can be created or modified manually.
```

2) `Filers are useful` ... should be **Filters**

3) Metrics - psutil
While there is a note for the requirement for **psutil** at the very bottom... it took me hours to figure out this was the issue. If this could be set as a Github markdown note (using ` > `) immediately under the title with more emphasis, this would save a lot of troubleshooting time. Something to the effect "IMPORTANT: Metrics requires **psutil** and will not appear in LogEntries unless this is installed.

Perhaps even better ... since logentries is now done via package management ... would it be possible to specify psutil as a required dependency during the yum install / apt-get install ?

5) System Stat Token
I realize this is beta, however there really is no documentation on this, it's functionality, how it differs from the metrics token, how to use it, etc?

6) Log Stats Distinction
The metrics section made sense for logging specific metrics into a defined log. I was unable to find any related information on logging what seems to be the CPU, Disk, and Bandwidth into the automated graphs section at the very top of the host section in the UI. Could the documentation be updated to include instructions/distinctions on this section and how to populate this data? I saw a couple screenshots in the LogEntries home page doc section; however, all it said was to install the agent (oh great, did that, now what?). Most DevOps and engineers tend to read through these source readme's much more thoroughly as the information contained within here is much more technical so having a discussion on how that works here would be incredible useful.
![image](https://cloud.githubusercontent.com/assets/739719/6204214/71b468c0-b4f7-11e4-8b04-5e96fafb0602.png)

7) Architecture Design Question
The `/etc/le/config` seems to store the majority of the information. The followed files seem to pick up whats been explicitly followed via the command as well as what's specified as followed within the host in the app(if i'm correct). I did not see any output of followed files in the config (Perhaps very useful if `pull-server-config` is false).  Would it be possible to specify a best practice installation rollout for environments that spin up lots of servers in an automated fashion.

Would the recommended course of action be either:
a) Install LE, register host with account key, then run multiple follow commands for the designated files?
or
b) Install LE, register host, and drop in enterprise config file (that includes follow options).

There seems to be a few ways to do things (even define followed files via the UI, see #74) so I'm perhaps just asking for some clarification in the direction of the agent.

Very pleased so far.

**Comment by StephenHynes7** [comment]
Hey Mark, thanks for the feedback here and I agree with the points made here. We will be look to address a number of these issues over the coming weeks! Thanks for the feedback.

We would also be interested in what you think of the Metrics and what you like to see with them moving forward (More UI iteration?)

**Comment by virgofx** [comment]
@StephenHynes7 Hi Stephen. Appreciate the prompt follow up and interest in making forward progress.

Basically, our team has been using logentries as centralized logging in an increasing fashion over the past years. The live tailing and bugs with the UI have been somewhat bothersome (when compared to papertrail); however, the small UI fixes (scrolling, toggling) have been getting fixed over time which has helped navigate the UI for log management.

We currently use a 3rd party service for server monitoring and application monitoring. I would bet this is pretty common for most small to medium teams (3-100 servers). The 3rd party service has typical reporting and alerting; however, lacks the log/traceability. 

To me, personally, it makes more sense to have that all in a central place. Therefore, we have been experimenting with trying to build the metrics data, reporting, and alerting over into logentries (as it would make more sense to have a single vendor provide this).

Aside from the few issues listed above, here are some general issues that have plagued us from really being able to "cancel" any 3rd party service and move forward.

**Likes**
* Agent is python, lightweight (no external dependencies). We are a huge advocate for nativeness.

**Dislikes / Requests**
* UI Dashboard is buggy. When opening the charts get squeezed to the left all overlapping.
* UI Dashboard does not have realtime refresh (Or atleast 5/10 second interval). Really need something more realtime(ish) for the manager types.
* Agent: The agent is *good*. In my opinion, it needs a lot of enterprise features to compete and really be used in large enterprise.  Things that would assist in automatically deploying tens of hundreds of servers using defined configuration options. Defining static configuration
* Agent: Define custom formatters. The default "'%s<14>1 %sZ %s %s - %s - hostname=%s appname=%s %s' %" is annoying. This should easily be customizable in another parameter in the config. Why? Let's say we want to define a clustered web app and instead of logging errors into each host's defined error log, we could just have a virtual host called "Web App" with errors all coming to same token. This way we could match the style with other custom defined.
* Dashboard/Searching - Aggregating CPU/Memory usage is really tough per host. Let's say we want to have a multiline timeline graph (This is common within most 3rd party services) where we aggregate CPU usage or network bandwidth per host. Let's say we have a cluster of 5 servers. Currently, performing a groupby in the search results in only doing a count .. no averages could be taken.
* Dashboard/Searching - Plucking custom information out 
* Agent: Custom Plugins - Would love the ability to define plugins. The out of box file following is great. Currently in our environment we have now setup Supervisor and created another PHP script that greps the Nginx stub status as well as pings an endpoint and pushes these to the same stats log that we created for the agent. Sample output is this.
```
[2015-02-16 18:02:57.566] [hostname] INFO: endpoint - https://clustered-web-app response.code=200 response.time=1.90 
[2015-02-16 17:47:39.977] [hostname] INFO: nginx - connections=1 accepts=1686 handled=1686 requests=1686 reading=0 writing=1 waiting=0 rpc=1
```
* Dashboard/Reporting - Using the above information, I want to report into the dashboard the current (e.g. the last reported active connections [1 above] -- so while there is average|count|sum .... there isn't a LIMIT or LAST VALUE OF. This would be useful for the current response time of the app as well. Therefore, the dashboard could have single custom text for things like:
Active Connections
Requests per Connection
# Slow Database Queries (even aggregate the top ones, could be done now with LE, but not 3rd party service)  -- Show table of top, as well as 

So intuitively. Basically just a way to incorporate small python plugins. These could easily be external files with a simple plugin format that is defined for us to extend that could be linked via the config file. It seems silly that we have to run a CLI PHP script in addition to the LE agent.

Think of a large scale deployment of web servers, database servers, caching servers. Using an automated deployment tool (Chef, Puppet, Ansible, Salt) we now define the settings as well as the logentries configuration options and plugins for each. We should be able to then install agent, drop in config file, restart service, and it should be good to go (automatically follow files, run plugins and report, automatically create hosts in UI, create logs in UI, etc).

* Alerting - Two-staged alerts. One of the features of 3rd party server monitoring is crossing a threshold and then reverting back. For example (X number of high responses (> 5 second) for web page -- maybe something is wrong -- Ok, send out an alert for Unusually High Response Time. Then 2 minutes later everything is normal, response time < 5 seconds for last say (3 x 5 second interval) -- so send out a Response Time Normal alert.  Currently, this would be impossible with logentries because the second alert needs to be only triggered if the first one was triggered.


Would be more than happy to chat with you guys about our future needs as well.

**Comment by vilda** [comment]
Hey Mark, thanks for the feedback. I'll put bug reports in UI aside and focus on the agent.

A1 - fixed in #78
A2 - fixed in #78
A3 - fixed in #80, psutil as dependency is already in pipeline
A5 - this is the first step in metrics so it may not feel completely integrated. Longer vision is that the destination for system stats would be created automatically in UI and the agent would be able to use it with minimal effort.
A6 - metrics are new, intended to replace old system stat collection. The new one is much more capable and scalable, it uses normal logs and will be usable in queries. The screenshot you provided is for old metrics that will be sunset.
A7 - will do #80

Custom formatters - it's relatively easy to implement if we find a good use case for them. The current format follows syslog (RFC5424) which is very good for scalable environments. It gives you automatically what you need most - timestamp, hostname, appname, msgid.
Using single token for all apps gives you exactly what you mentioned. The documentation may not be clear about it, tried to fix it in #80.

Custom plugins - we already have some proposal for lightweight plugins. We try to get balance about functionality wired in the agent and other high-potential specialized tools like diamond https://github.com/BrightcoveOS/Diamond.

Alerting - these are good point, we'll have a look how to implement them.

**Comment by StephenHynes7** [comment]
We even have support Diamond :) https://github.com/BrightcoveOS/Diamond/blob/master/src/diamond/handler/logentries_diamond.py

**Comment by virgofx** [comment]
@vilda @StephenHynes7  Very cool. I'm not familiar with Diamond per say but it looks like it pushes to Graphite. What's the correlation to graphite and Logentries in terms of end-users/clients who are using only Logentries?

e.g. What's the direction of pushing all log data into the [ stats/metrics ] log of a host and having logentries report on it (obviously better UI/dashboards are needed as well as aggregates/host distinctions/groupbys/last value of) ?  Or does LE just want to collect the data and offload it elsewhere ? (Graphite? ) (Managed by end-users?)

Looking forward to the updated documentation. I already found the readme very thorough, but as an advanced user, I even wanted to do more -- e.g. create custom formatters and custom plugins for php-fpm, redis, nginx, and have those report accordingly. If there was just capability to define something similar like as follows below, this would allow functionality to exist all within the logentries daemon.

```
# /etc/le/config
[main]
....

[ custom-plugin ]
plugin = /path/to/plugin.py
interval = 7
```

```
# /path/to/plugin.py
# Not a python expert, but somehow a definition that can either extend, or is declared a specific way, or requires a custom return type?

# Perform some unique functionality, e.g.
#  1. curl - 127.0.0.1/nginx_status
#  2. grep connections
#  3. return formatted string [ connections=X active=Y requests=Z ]
```

**Comment by mrud** [comment]
@virgofx we also have a Logentries handler for diamond, e.g. you can push directly from diamond to Logentries. We are also working together with Hosted Graphite as well as Geckoboard to export the data from the le dashboard.

**Comment by vilda** [comment]
We are moving towards new metrics. Since the support for it is not complete yet in the UI, we keep it in github's documentation for now. Once this is finished we'll update documentation on main site and adjust UI accordingly (more work ahead). Sorry for the confusion.

I'll forward your comments regarding query language to get it sorted - thanks again. There is a work on second-generation querying (actually two languages) in progress and your comments will be also helpful.

I put custom plugins on my TODO list. We'll have a look on it soon-ish.

Thanks!

**Comment by virgofx** [comment]
@vilda Makes sense. Looking forward to the updated query language and revamped metrics.
