### ISSUE TITLE
Agent does not send log data if suppress_ssl=True is set in the local Config

### ISSUE THREAD

**Issue by StephenHynes7** [logentries/le#76]
Users who are upgrading from older versions of the Agent may encounter an issue where no log data is being sent to Logentries.

In such a open up /etc/le/config. Check if the field "suppress_ssl=True" or "ec2eu = True" exist. If they do remove them.

Then restart the Agent service.

**Comment by StephenHynes7** [comment]
We should have a fix for this incoming ASAP

**Comment by vilda** [comment]
Does #73 fixes this (it imports fix from your MR)?
