### ISSUE TITLE
MIT PGP Key Server can't find C43C79AD

### ISSUE THREAD

**Issue by Umofomia** [logentries/le#84]
The MIT PGP key server reports your key doesn't exist when attempting to add the Logentries release key with your documented command:

```sh
gpg --keyserver pgp.mit.edu --recv-keys C43C79AD && gpg -a --export C43C79AD | apt-key add -
```

```
STDOUT: gpgkeys: key C43C79AD not found on keyserver
 STDERR: gpg: requesting key C43C79AD from hkp server pgp.mit.edu 
gpg: no valid OpenPGP data found. 
gpg: Total number processed: 0
```

**Comment by vilda** [comment]
vilda@uscale:~$ gpg --keyserver pgp.mit.edu --recv-keys C43C79AD
    gpg: requesting key C43C79AD from hkp server pgp.mit.edu
    gpg: key C43C79AD: "Logentries Release Key <info@logentries.com>" not changed
    gpg: Total number processed: 1
    gpg:              unchanged: 1

It's happening sometimes. You may try Ubuntu keyserver `keyserver.ubuntu.com`

**Comment by Umofomia** [comment]
It looks like this was a temporary issue.

**Comment by mhalligan** [comment]
This issue happens to me quite frequently. Is there a more reliable keyserver to use?

**Comment by vilda** [comment]
You may try Ubuntu keyserver `keyserver.ubuntu.com`. Alternatively you can import the key explicitly - store it in a file or inside a script.
