### ISSUE TITLE
metrics-space = /  when using multiple partitions

### ISSUE THREAD

**Issue by michael-seibert-le** [logentries/le#87]
What if one has multiple partitions on a system?
as in:

Filesystem Size Used Avail Use% Mounted on 
/dev/sda2 20G 1.4G 18G 8% / 
tmpfs 95G 0 95G 0% /dev/shm 
/dev/sda1 477M 67M 385M 15% /boot 
/dev/sda7 5.8G 13M 5.5G 1% /tmp 
/dev/sda3 16G 4.8G 11G 33% /usr 
/dev/sda6 7.8G 1.4G 6.1G 19% /var 
/dev/zd0p1 2.0T 1.2T 919G 56% /ppro 
vol1/images 1.5T 589G 912G 40% /images 
vol0 509G 256K 509G 1% /vol0 
vol1 916G 4.8G 912G 1% /vol1

**Comment by vilda** [comment]
Use space as a delimiter between them. If the documentation is not clear enough, would you create a MR with improvement or send me email with it?
